### ISSUE TITLE
"Failed to find your location.."

### ISSUE THREAD

**Issue by fastone** [codebutler/foursquarex#19]
"Failed to find your location: The operation couldn't be completed. (kCLErrorDomain error 0.)"

**Comment by codebutler** [comment]
Hey,

This error is usually just temporary, and seems to mean one or more of "not enough wifi nearby", "skyhook is down", "i don't feel like figuring out where you are, go away". I'll make this show a more friendly error in the next release.

Have you been able to use FoursquareX since getting this error?

**Comment by codebutler** [comment]
Better error message if location not found. Closed by 40bf6baef8e9787339f84fd661df2c08bbec3db7.
